cask_args appdir: "/Applications"

tap "heroku/brew"
tap "prisma/prisma"

# Mas-cli
mas "LiveReload", id: 482898991
mas "Bear", id: 1091189122

# Casks
cask "hyper"
cask "visual-studio-code"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "spotify"
cask "docker"
cask "xquartz"
cask "authy"
cask "krita"
cask "the-unarchiver"
cask "vmware-fusion"
cask "adobe-creative-cloud"
cask "homebrew/cask-versions/sequel-pro-nightly"
cask "graphql-playground"
cask "bettertouchtool"
cask "private-internet-access"
cask "protonmail-bridge"
cask "protonvpn"
cask "backblaze"
cask "discord"
cask "balenaetcher"
cask "nextcloud"
cask "iina"

# Brews
brew "mackup"
brew "zsh"
brew "wget"
brew "vim"
brew "heroku/brew/heroku"
brew "asciinema"
brew "ctags"
brew "prisma"
brew "neovim"
brew "mysql"
brew "python"
brew "python3"
brew "fswatch"
brew "node"
brew "shellcheck"

# Install some CTF tools
brew "aircrack-ng"
brew "bfg"
brew "binutils"
brew "binwalk"
brew "cifer"
brew "dex2jar"
brew "dns2tcp"
brew "fcrackzip"
brew "foremost"
brew "hashpump"
brew "hydra"
brew "john"
brew "knock"
brew "netpbm"
brew "nmap"
brew "pngcheck"
brew "socat"
brew "sqlmap"
brew "tcpflow"
brew "tcpreplay"
brew "tcptrace"
brew "ucspi-tcp"
brew "xpdf"
brew "xz"

cask "burp-suite"

# Install other useful binaries.
brew "ack"
brew "git"
brew "git-lfs"
brew "ssh-copy-id"
